config/routes.rb
Rails.application.routes.draw do
  get 'search',to: "search#index"
  
  resources :user
  resources :posts do 

    resources :comments

  end
  resources :invitations
  resources :likes , only: [:create,:destroy]
  
  patch "accept",to: "invitations#accept"


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/views/shared/_friend.html.erb
<h1>Friends</h1>
<%@u = current_user%>    
       <%@pending = @u.pending_invitations%>

      <div class = "d-flex flex-wrap ">
<%@user.each do |a|%>
<%@b = a%>

               <%ab = Invitation.where(friend_id: current_user.id,user_id: a.id) %>
          <%if @pending.include?(ab[0])%>
                  <%next%>
           <%else%>
                   <%if a.id != current_user.id%>
                                    <%inv = Invitation.where(user_id: current_user.id,friend_id: a.id) %>
                                            <%if inv.empty?%>
                                            <%inv = Invitation.where(friend_id: current_user.id,user_id: a.id) %>
                                          <%end%>        
              <% if current_user.friend_with?(a)%>


                                        <div class="card" style="width: 12rem;margin-right: 30px;margin-bottom: 30px;">
                      
                      <%if a.image.attached?%>
                     <%= image_tag a.image,width: "30px",class:"card-img-top",style:"height: 8rem;"%> 
                     <%end%>
                            <div class="card-body">
                              <h5 class="card-title"><%=a.fname%> <%=a.lname%> </h5>
                              <p class="card-text">Email: <%=a.email%></p>
                            </div>


                           <div class="card-body"style="display: flex;justify-content: space-evenly;">
                            <p class="card-link">
                              <%=link_to "unfriend","/invitations/#{inv.ids[0]}", class: "btn btn-danger",data: {"turbo-method": :delete}%>
                            
                            </p>

                            
                           <p class="card-link">
                                        <%=link_to "Pofile",invitation_path(@b), class: "btn btn-info",method: :get%>
                            
                            </p>

                          </div>
                          </div>
              <%end%>
        <%end%>

  <%end%>
  <%end%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light "style="background-color: #3b5998; color: white ">
  <div class="container-fluid">
    <%# <a class="navbar-brand" href="#">FaseBook</a> %>
    <%= link_to "Fasebook",root_path,class: "navbar-brand"%>


          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      


                  <%if user_signed_in?%>

              </li>
           <%if current_user.image.attached?%>
               <%= image_tag current_user.image,width: "50px"%>
               <%end%>
            </li>
            <li>
              <%= link_to "Find Friends", user_index_path,class: "nav-link active"  %>
            </li>
            <li>
                <%= link_to "Friend Request", invitations_path,class: "nav-link active"  %>
            </li>
            <li>
                  <%=link_to "Profile",user_path(current_user),class: "nav-link active"%>
            </li>
             <li>
                    <%= link_to "Edit Your Profile",  edit_user_registration_path ,class: "nav-link active" %>
            </li>
             <li>

                     <%= link_to "Log out", destroy_user_session_path,data: {"turbo-method": :delete}, class: "nav-link active" %>
            </li>

                <ul calss= "navbar-nav" style="margin-left: 270px">
                        <%=render 'search/form'%>
                </ul>


            <%else%>

                    <li class="nav-item">
                        <%=link_to "Sing UP " ,new_user_registration_path,class: "nav-link"%>
                    </li>
                    <li class="nav-item">
                          <%=link_to "Log In " , new_user_session_path,class: "nav-link active"%>
                    </li>

            <%end%>
     
            </ul>
                </div>
              </div>
            </nav>

app/views/shared/_profile.html.erb
<%a = current_user%>

<h2> Your friends Profile <h2>

<p><%= image_tag a.image,width: "200px"%></p>
<p>Name: <%=a.fname%> <%=a.lname%><p>
<p>Email:<%=a.email%></p>