config/routes.rb
Rails.application.routes.draw do
  get 'search',to: "search#index"
  
  resources :user
  resources :posts do 

    resources :comments

  end
  resources :invitations
  resources :likes , only: [:create,:destroy]
  
  patch "accept",to: "invitations#accept"


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user

  def self.reacted?(id1,id2)

    case1 = !Invitation.where(user_id: id1,friend_id: id2).empty?
    case2 = !Invitation.where(user_id: id2,friend_id: id1).empty?
 
      case1 || case2
  end

def self.confirmed_record?(id1,id2)

  case1 = !Invitation.where(user_id: id1,friend_id: id2,confirmed: true).empty?
  case2 = !Invitation.where(user_id: id2,friend_id: id1,confirmed: true).empty?

  case1 || case2

end

def self.find_invitation(id1,id2)
 if Invitation.where(user_id: id1,friend_id: id2,confirmed: true).empty?
  Invitation.where(user_id: id2,friend_id: id1,confirmed: true)[0].id
  
  
 else
  Invitation.where(user_id: id1,friend_id: id2,confirmed: true)[0].id
  
 end


end


end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!
  def index
  
    @user = current_user
    
    @pending = @user.pending_invitations
    # end
    @friends = Invitation.all.select{ |m| m.confirmed == true || (m.user_id == @user.id || m.friend_id == @user.id)}

   
  end

  def new
  end
  def show
      @b= User.find(params[:id])
  end
  def create

    # debugger
    @invitation = current_user.invitations.create(invite_params)
    if @invitation.save
      redirect_to request.referrer
    else
      render all_user_path
    end
  end

  def accept
    
    @invitation = Invitation.find(params[:id])
    accept = @invitation.update(invite_params)
    redirect_to request.referrer
  end

  def destroy
    
    @invitation = Invitation.find(params[:id])
    @invitation.destroy
    redirect_to request.referrer


  end

  private

  def invite_params
    params.permit(:friend_id,:confirmed)
  end
      
    
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/index.html.erb
<h3> Friend Requests</h3>

<% if !@pending.empty? %>

<% @pending.each do |p| %>

                <%inv= p.id%>


            <%if current_user.friend_with?(p.user)%>
                    <p>Friends</p>
                    <%=p.user.fname%>
                    <br>
            <%else%>
                                <div class = "d-flex flex-wrap">
                                        
                                        <div class="card" style="width: 10rem; margin-right: 20px;">
                        <%# <img class="card-img-top" src="..." alt="Card image cap"> %>
                         <%if p.user.image.attached?%>
                          <div class="rounded mx-auto d-block my-3">
                           <%= image_tag p.user.image,width: "30px",class: "card-img-top",style:"height: 8rem;"%> 
          
                        <%end%>
                                                
                        <div class="card-body">
                        <h5 class="card-title"> <%=p.user.fname%> <%=p.user.lname%></h5>

                        <p class="card-text">Email: <%=p.user.email%></p>
                        </div>
                         <div class="row">
                        <div class="card-body"style="display: flex;justify-content: space-evenly;">
                      
                        <p class="card-link"> <%= button_to "Accept",accept_path, params: {id: p.id,confirmed: true}, method: :patch,class: "btn btn-primary"%> </p>
                        <p class="card-link"> <%=link_to "Reject","/invitations/#{inv}", class: "btn btn-primary",data: {"turbo-method": :delete}%></p>
                        </div>
                        </div>
                        </div>
                          </div>

          <%end%>
        
  <%end%>


  <%else%>
         
<p>No pending Request</p>
<%end%>



    

app/views/invitations/show.html.erb
<h2> <%=@b.fname%> Profile </h2>
 <%if @b.image.attached?%>
<p><%= image_tag @b.image,width: "200px"%></p>
<%end%>
<p>Name: <%=@b.fname%> <%=@b.lname%><p>
<p>Email:<%=@b.email%></p>


<%posts = @b.posts.all%>
<div class= "container">
<%posts.each do|post|%>

 <p class="card-text">
    <strong>By:</strong>
    <%= post.user.fname %>
  </p>

<div class="card" style="width: 15rem;" >


  <div class = "d-flex flex-wrap">
        <div class="rounded mx-auto d-block my-3">

  <%if post.avatar.attached?%>
    <strong>Avatar</strong><br>

  <%= image_tag post.avatar,width: "200px",style:"height: 8rem;"%>
<%end%>

  <p>
 

  <%if post.images.attached?%>
      <strong>Images</strong><br>
  <%post.images.each do |image|%>


  <%= image_tag image,width: "200px",style:"height: 8rem;"%>
  
  <%end%>
<div class = "mb-3">
   <%# <strong>Body:</strong> %>
    <%= post.body %>
    </div>
<%end%>

</div>

</div>
</div>

   

      
    </p>
  </p>


   


  <%# <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p> 
</div>
<%end%>
</div>