config/routes.rb
Rails.application.routes.draw do
  get 'search',to: "search#index"
  
  resources :user
  resources :posts do 

    resources :comments

  end
  resources :invitations
  resources :likes , only: [:create,:destroy]
  
  patch "accept",to: "invitations#accept"


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments,dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  has_many_attached :images, dependent: :destroy




end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  before_action :authenticate_user!
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post=current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :user_id,:avatar,images: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>
<!--
  <div class= "mb-3">
  <%= form.label :avatar%> 
  <%= form.file_field :avatar %>
  </div>-->
   <div class= "mb-3">
  <%= form.label :images%> 
  <%= form.file_field :images,multiple: true %>
  </div>

  <div  class= "mb-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">

 <p class="card-text">
    <strong>By:</strong>
    <%= post.user.fname %>
  </p>

<div class="card" style="width: 15rem;" >


  <div class = "d-flex flex-wrap">
        <div class="rounded mx-auto d-block my-3">

  <%if post.avatar.attached?%>
    <strong>Avatar</strong><br>

  <%= image_tag post.avatar,width: "200px"%>
<%end%>

  <p>
 

  <%if post.images.attached?%>
      <strong>Images</strong><br>
  <%post.images.each do |image|%>


  <%= image_tag image,width: "200px",style:"height: 12rem;"%>
  
  <%end%>
<div class = "mb-3">
   <%# <strong>Body:</strong> %>
    <%= post.body %>
    </div>
<%end%>

</div>

</div>
</div>

   

      
    </p>
  </p>


   


  <%# <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p> 
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= button_to "New post", new_post_path,class: "btn btn-info",method: :get %>
<%# <%= link_to "New post", new_post_path %> 



<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
    



<%=post.likes.count%> likes
<%like = current_user.likes.find_by(post: post)%>


<%if like.nil?%>

  <%=button_to "Like", likes_path,params:{like:{post_id: post.id}},class: "btn btn-success",method: :post, remote:true%>


<%else%>
 <%=button_to "Unike", like_path(like),class: "btn btn-danger",data: {
 "turbo-method": :delete
},method: :delete%>

<%end%>


 <%= link_to "Show this post", post,class: "btn btn-secondary" %>
    </p>

  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<%=@post.likes.count%> likes
<%like = current_user.likes.find_by(post: @post)%>


<%if like.nil?%>

  <%=button_to "Like", likes_path,params:{like:{post_id: @post.id}},class: "btn btn-success",method: :post%>


<%else%>
 <%=button_to "Unike", like_path(like),class:"btn btn-danger",data: {
 "turbo-method": :delete
},method: :delete%>

<%end%>
<div>

  <%= link_to "Back to posts", posts_path %><br>

<% if current_user.id == @post.user_id%>
    <%= link_to "Edit this post", edit_post_path(@post) %> |  
  <%= button_to "Destroy this post", @post, method: :delete %>
  <%end%>
</div>


<%= render @post.comments%>
<h5>Add a comment</h5>
<%= render partial: "comments/form"%>